/* gc-scene — make a moving scene for somebody's friend, and report on one.
   ─────────────────────────────────────────────────────────────────────────
   POST { owner_key, portrait, where, seconds }  -> { job_id }
   GET  ?job_id=...                              -> { status, note, ready }
   GET  ?job_id=...&file=1                       -> the mp4 itself

   A friend you build comes with one still picture. This is what turns a
   picture into a scene, and it is the machinery behind the Scene two, three,
   four, five slots in the room.

   NO BACKGROUND FUNCTION, copied deliberately from etl-design-animate, which
   learned this the hard way: starting a Veo render is a sub-second call that
   returns an operation name, so POST does it directly, and GET polls that
   operation and finishes the job when it is done. Handing off to a background
   worker gave six runs in a row that reported 'running' and then sat on
   'queued' forever, because Netlify answered the invocation with 202 and never
   ran it. The thing that completes the job is the thing already asking about
   it, so there is no invocation left to fail silently.

   THEY HAVE TO LOOK UP. Dr. O rejected a finished clip of Arch doing woodwork
   for exactly one reason: "he never looked up. I could not have that for a
   companion video." A person absorbed in a task is footage of somebody who
   does not know you are there, and a scene is supposed to be somebody sitting
   WITH you. That instruction is added to every prompt here rather than left to
   whoever writes the description, because getting it wrong costs a whole
   render and only shows up at the end.

   IT SPENDS REAL MONEY, SO IT IS OWNER ONLY. Veo Lite takes an input frame at
   five cents a second, which is the whole reason this is affordable, and the
   ladder in _veo-video.js steps up to the standard tier at forty if Lite
   refuses. Four seconds is twenty cents at best and a pound sixty at worst,
   per press. No visitor gets to spend that: scenes are sold and then made,
   not generated by anybody who finds the endpoint.
*/

const { getStore, connectLambda } = require('@netlify/blobs');
const Stripe = require('stripe');
const sharp = require('sharp');
const veo = require('./_veo-video.js');
const notify = require('./_gc-notify.js');

/* CROPPED TO 16:9 BEFORE IT EVER REACHES VEO, added 2026-08-20. Real bug,
   found from a real delivered clip: Dr. O, "not the right size" -- a
   pillarboxed, roughly-9:16 video sitting in a stage that is 16:9 by CSS
   (see room.html's own note on that). Checked the actual stored portrait
   rather than guessing: 768x1376, ratio 0.558. Veo inherits the INPUT
   frame's own aspect ratio for image-driven generation and ignores the
   aspectRatio parameter entirely when a first frame is supplied -- the
   parameter still gets sent (harmless) but the shape of the source image
   is what actually decides the output shape.

   FACE-AWARE CROP, not a plain center crop: a portrait this tall cropped
   to 16:9 around dead center would very likely cut through the face.
   sharp's 'attention' strategy finds the most visually salient region
   (faces, edges, high-detail areas) and crops toward that instead of
   assuming the subject is centered.

   WAS A PLAIN "COVER" CROP, replaced 2026-08-20, same day: Dr. O approved
   this direction over padding at the time, but a full "cover" crop from a
   portrait this narrow is not a strategy choice, it is forced geometry --
   768x1376 into 1280x720 only ever keeps about 31% of the original height
   no matter which sharp position strategy picks it, because "cover" scales
   until the width matches and crops away whatever height that leaves.
   "attention" cannot zoom out further than that; there is no more image to
   give it. Confirmed on a real production render: "no talking, but I lost
   her face" -- forehead to chin, no hair, no neck, no room.

   HYBRID CROP NOW, tested and shown to her as a still image before this
   ever touched production (she did not object to the framing, only never
   got wired in): keep a real, moderate zoom -- about 65% of the original
   height, biased toward the top so there is headroom rather than a
   dead-center crop through the eyes -- then fill the remaining width with
   a heavily blurred, scaled-up copy of the SAME crop as a backdrop, not
   flat black bars. Shows hair, neck, shoulders, a hint of the room; still
   reads as close and present, not shrunk into a wide empty frame. */
async function cropTo169(base64) {
  const buf = Buffer.from(base64, 'base64');
  const meta = await sharp(buf).metadata();
  if (!meta.width || !meta.height) return base64;   // unreadable, send it through unchanged rather than fail the whole render
  const targetRatio = 16 / 9;
  const currentRatio = meta.width / meta.height;
  if (Math.abs(currentRatio - targetRatio) < 0.02) return base64;   // already close enough, no point re-encoding

  const targetW = 1280, targetH = 720;
  const cropH = Math.min(meta.height, Math.round(meta.height * 0.65));
  const cropped = await sharp(buf)
    .extract({
      left: 0,
      // Biased up (0.35 rather than 0.5/centered), so what survives is
      // headroom-down-to-chest, not a band centered through the eyes.
      top: Math.max(0, Math.round((meta.height - cropH) * 0.35)),
      width: meta.width,
      height: cropH,
    })
    .toBuffer();
  const croppedMeta = await sharp(cropped).metadata();

  const scale = targetH / croppedMeta.height;
  const fgWidth = Math.min(targetW, Math.round(croppedMeta.width * scale));
  const fg = await sharp(cropped).resize(fgWidth, targetH).toBuffer();

  const bg = await sharp(cropped)
    .resize(targetW, targetH, { fit: 'cover' })
    .blur(50)
    .toBuffer();

  const composed = await sharp(bg)
    .composite([{ input: fg, left: Math.round((targetW - fgWidth) / 2), top: 0 }])
    .jpeg({ quality: 92 })
    .toBuffer();
  return composed.toString('base64');
}

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization',
};

const json = (status, obj) => ({
  statusCode: status,
  headers: { ...CORS, 'Content-Type': 'application/json', 'Cache-Control': 'no-store' },
  body: JSON.stringify(obj),
});

const STORE = 'gc_scene_jobs';

/* THREE, not unlimited: added 2026-08-20 alongside the retry-on-filter fix
   below. A real repro succeeded on attempt two, so three is a real margin,
   not a guess -- and a ceiling still matters even though a filtered attempt
   is free, since this is a poll loop and a job that retries forever is a
   job that never reaches an order sitting in 'paid' waiting to be refunded
   if it truly cannot be made. */
const MAX_VEO_ATTEMPTS = 3;

/* ── THE PROMPT THAT ALREADY WORKS ───────────────────────────────────────────
   Not invented here. This is Dr. O's own wording from the Flow sessions that
   produced Arch's five clips, which she made by hand with no editing after and
   judged "perfectly fine". Automating that means using her prompt, not a
   reasonable-sounding one of mine.

   Hers, verbatim in shape: "A seamless infinite loop of this man sitting in
   front of a wood fireplace in a log cabin, but have him look over at the
   camera. Static camera, fixed framing, consistent soft lighting throughout.
   Minimal body movement."

   THE LOOP IS THE PART I HAD MISSED. The room plays these with the loop
   attribute, so a clip that does not end where it began jumps every few
   seconds and the person twitches. Every one of her prompts opens with
   "a seamless infinite loop" and that is why hers sit quietly under a
   conversation.

   FIXED FRAMING AND CONSISTENT LIGHTING do the same job: across a loop point,
   a drifting camera or a changing light is exactly where the seam shows.

   LOOKING AT THE CAMERA is hers too, in every prompt, and it is the thing she
   rejected a finished clip over.

   HER TEMPLATE, WITH ONE SLOT. Given exactly:

     "A seamless infinite loop of this man [sitting in front of a wood
      fireplace in a log cabin]. Static camera, fixed framing, consistent soft
      lighting throughout. Minimal body movement, fluid and natural repetition
      where the ending seamlessly matches the starting frame, no jump cuts. Do
      not change his looks, but change his clothes to a plaid shirt and jeans."

   Everything outside the bracket is fixed and the caller fills the bracket.
   Writing it any other way is how a proven prompt quietly becomes a different
   one.

   DO NOT CHANGE HIS LOOKS is the line I would not have thought to write and
   the one that matters most. Somebody chose that face out of four. A scene
   that drifts it is not their friend any more, and the drift would arrive
   looking like a quality problem rather than the identity problem it is.

   THE ENDING MATCHING THE STARTING FRAME is the loop said twice, from both
   ends. The room plays these on loop and the seam is the whole risk. */

function scenePrompt({ where, gender, clothes }) {
  /* "this man" is hers because Arch is one. The friend carries a gender and
     the prompt has to follow it, or every woman somebody builds is described
     to the model as a man. */
  const g = String(gender || '').toLowerCase();
  const isWoman = /woman|female|she/.test(g);
  const isMan   = !isWoman && /man|male|\bhe\b/.test(g);
  const subject = isWoman ? 'this woman' : isMan ? 'this man' : 'this person';

  /* PRONOUNS FOLLOW THE SUBJECT. It read "this man ... They look over", which
     is a small inconsistency to hand a model whose one hard instruction is not
     to change who it is looking at. */
  const single = isWoman || isMan;              // "they" takes plural verbs
  const they  = isWoman ? 'She'  : isMan ? 'He'  : 'They';
  const their = isWoman ? 'her'   : isMan ? 'his' : 'their';
  const are   = single ? 'is' : 'are';
  const looks = single ? 'looks' : 'look';

  const bits = [];
  bits.push('A seamless infinite loop of ' + subject + ' ' + String(where).trim().replace(/\.$/, '') + '.');
  bits.push('Static camera, fixed framing, consistent soft lighting throughout.');
  bits.push('Minimal body movement, fluid and natural repetition where the ending seamlessly ' +
            'matches the starting frame, no jump cuts.');

  /* LOOKING AT THE CAMERA sits in every Flow prompt she wrote, worded into the
     scene itself: "but have him look over at the camera". It is not optional
     and it is not the caller's to forget, because she rejected a finished clip
     over precisely this and a render only reveals it at the end.

     REPLACED 2026-08-20. The line this replaced ("present, as though sitting
     with them... not absorbed in a task... not talking and there is no
     speech") was never actually hers -- her own real template above has no
     anti-talking clause at all, because Arch's own prompts never described
     him as present/watching/listening in the first place. That extra
     framing was added later for built friends, and it is exactly what kept
     producing a talking clip: three different real renders, two different
     wordings of "do not talk," on two different tiers, all still talked --
     one of them a full spoken sentence. What actually worked, tested the
     same day directly against Isabelle's own portrait: her own short,
     original phrasing, unelaborated. "Active listening" reads as a quieter,
     more ambient state to the model than "present, watching, sitting with
     them," and a short "no talking" outperformed a longer, more insistent
     version of the same instruction -- over-explaining what NOT to do drew
     more attention to talking, not less. */
  bits.push(they + ' ' + are + ' active listening, ' + looks + ' over at the camera. No talking.');

  /* Her last clause, and optional the way she used it. */
  bits.push(clothes
    ? 'Do not change ' + their + ' looks, but change ' + their + ' clothes to ' +
      String(clothes).trim().replace(/\.$/, '') + '.'
    : 'Do not change ' + their + ' looks.');

  return bits.join(' ');
}

function newJobId() {
  /* Unguessable, because the GET side is not owner-gated: knowing a job id is
     how the browser that started it collects the result. */
  const r = require('crypto').randomBytes(9).toString('hex');
  return 'gcs-' + r;
}

/* ── THE REFUND GAP, CLOSED ───────────────────────────────────────────────
   Added 2026-08-19. Isabelle's own order failed twice and nothing noticed
   -- no refund, no email, an order sitting at 'paid' forever with no way
   for the person who paid to know anything had gone wrong. Dr. O: "fix the
   refund gap first," ahead of digging further into why that render kept
   failing. That priority is the point: a customer left in limbo after
   being charged is a worse problem than one failed video.

   REFUNDS AUTOMATICALLY, ON THE FIRST FAILURE, ON PURPOSE. There is no
   automatic retry (fulfillment here is a queue a person works through by
   hand, not a live loop), so a failure that goes unrefunded stays
   unrefunded until somebody happens to notice. Take the money, then make
   the thing; if the thing cannot be made, the money goes back the same
   way, without waiting on a person to catch it. Whoever fulfils an order
   can always charge again for a deliberate retry with a different image --
   that is a real, available path. Leaving someone charged for nothing
   with no idea why is not. */
async function refundOrder(order, reason) {
  const stripeKey = process.env.STRIPE_SECRET_KEY;
  if (!stripeKey) {
    console.warn('[gc-scene] cannot refund, no STRIPE_SECRET_KEY:', order.order_id);
    return { refunded: false, reason: 'no STRIPE_SECRET_KEY set on this site' };
  }
  if (!order.session_id) {
    /* An order can reach here without ever having been marked paid by a
       real session (unpaid_on_purpose renders, an apology, a fix) -- there
       is no real charge behind it, so there is nothing to refund. Not an
       error, just nothing to do. */
    return { refunded: false, reason: 'no session_id on this order, nothing was charged' };
  }

  const stripe = new Stripe(stripeKey, { apiVersion: '2024-06-20' });
  let refund;
  try {
    const session = await stripe.checkout.sessions.retrieve(order.session_id);
    if (!session || !session.payment_intent) {
      return { refunded: false, reason: 'session has no payment_intent' };
    }
    refund = await stripe.refunds.create({ payment_intent: session.payment_intent });
  } catch (err) {
    console.warn('[gc-scene] stripe refund failed:', err && err.message);
    return { refunded: false, reason: String((err && err.message) || err) };
  }

  const orders = getStore('gc_scene_orders');
  order.status = 'refunded';
  order.refunded_at = new Date().toISOString();
  order.refund_id = refund.id;
  order.refund_reason = reason;
  await orders.setJSON(order.order_id, order);

  const told = await notify.refunded(order, reason);
  return { refunded: true, refund_id: refund.id, told };
}

exports.handler = async (event) => {
  if (event.httpMethod === 'OPTIONS') return { statusCode: 204, headers: CORS, body: '' };

  const qs = event.queryStringParameters || {};
  let body = {};
  try { body = JSON.parse(event.body || '{}'); } catch (_) {}

  try { connectLambda(event); } catch (_) {}
  let store;
  try { store = getStore(STORE); } catch (e) { return json(500, { error: 'store_unavailable' }); }

  /* ── start one ─────────────────────────────────────────────────────────── */
  if (event.httpMethod === 'POST') {
    const owner = String(body.owner_key || '').trim();
    if (!process.env.OWNER_KEY || owner !== process.env.OWNER_KEY) {
      return json(403, { error: 'owner_only' });
    }

    /* The still to animate. Sent as base64 without a data: prefix, because
       that is what Veo takes and stripping it here means the caller does not
       have to know that. */
    let portrait = String(body.portrait || '');
    portrait = portrait.replace(/^data:image\/[a-z+]+;base64,/i, '').trim();

    let where = String(body.where || '').trim();
    let gender = body.gender;
    let order = null;

    /* FULFILLING AN ORDER, WITHOUT MOVING THE PICTURE BY HAND. Somebody asked
       for a scene through gc-scene-order and their portrait is already stored;
       passing order_id here reads it back rather than making whoever is
       fulfilling it download a megabyte and paste it into a request. What they
       asked for comes with it, so the scene made is the scene ordered. */
    if (body.order_id) {
      const orders = getStore('gc_scene_orders');
      order = await orders.get(String(body.order_id), { type: 'json' });
      if (!order) return json(404, { error: 'order_not_found' });

      /* TAKE THE MONEY, THEN MAKE THE THING, ENFORCED HERE RATHER THAN
         REMEMBERED. Without this the payment step is decorative: anybody
         fulfilling a queue at speed would render whatever is in front of them,
         and an unpaid order looks exactly like a paid one at a glance.

         Overridable on purpose, because there are real reasons to make a scene
         nobody paid for: a demo, an apology, a fix for one that came out wrong.
         It has to be asked for in so many words. */
      if (order.status === 'waiting' && !body.unpaid_on_purpose) {
        return json(402, {
          error: 'not_paid',
          detail: 'That order has not been paid for. Send unpaid_on_purpose to make it anyway.',
        });
      }
      /* "I ALREADY HAVE MY OWN," added 2026-08-20. Two shapes, both skip the
         Veo source entirely when they can:

         own_vimeo_id needs no render at all -- their own video is already
         made and already hosted, so this delivers it directly (below) and
         returns before Veo is ever touched, exactly the same shape as the
         normal delivery block further down in this file, just without a
         job in between.

         own_photo_key is the other real case the crafting-photo test
         proved out: their own photo stands in for the friend's stored
         portrait as Veo's source, same pipeline (crop, prompt, retry-on-
         filter) as any other render from here down. */
      if (order.own_vimeo_id) {
        const link = 'https://emerging-tech-lab.com/good-company/room.html' +
          '?add-scene=' + encodeURIComponent('vimeo:' + order.own_vimeo_id) +
          (order.own_thumb_key
            ? '&thumb=' + encodeURIComponent('/.netlify/functions/gc-scene-order?order_id=' + order.order_id + '&thumb=1')
            : '') +
          '&label=' + encodeURIComponent('A new scene');
        const told = await notify.sceneReady(order, link);
        order.status = 'made';
        order.link = link;
        order.told = told;
        await orders.setJSON(order.order_id, order);
        console.log('[gc-scene] order ' + order.order_id + ' delivered (own vimeo):',
                    told.sent ? told.to : 'not sent (' + told.reason + ')');
        return json(200, { ok: true, delivered: true, own_vimeo_id: order.own_vimeo_id, link });
      }

      if (!portrait) {
        portrait = String(await orders.get(order.own_photo_key || order.portrait_key, { type: 'text' }) || '').trim();
      }
      if (!where) where = order.where || 'sitting quietly, present';
      if (!gender) gender = order.gender;
    }

    if (!portrait) return json(400, { error: 'portrait_required' });
    if (!where) return json(400, { error: 'where_required' });

    /* Four seconds by default and eight at most. Duration is the only real
       lever on what this costs, and the helper clamps it too. */
    const seconds = Math.min(8, Math.max(4, Number(body.seconds) || 4));

    /* LITE OR NOTHING, UNLESS SOMEBODY SAYS OTHERWISE IN SO MANY WORDS.
       The shared ladder steps Lite up to the standard tier on a refusal, which
       is eight times the price: four seconds goes from twenty cents to a pound
       sixty, and four scenes from $1.60 to $12.80. Dr. O on that number: "no".

       So the ceiling is explicit here. A refusal comes back as a refusal, which
       costs nothing, and stepping up is a decision somebody makes on purpose by
       sending allow_standard rather than something discovered from a bill. */
    const ladder = body.allow_standard ? [veo.MODEL_LITE, veo.MODEL_FULL] : [veo.MODEL_LITE];

    const prompt = scenePrompt({ where, gender, clothes: body.clothes });

    /* SIXTEEN BY NINE, BECAUSE THAT IS THE SHAPE OF THE ROOM. The video area
       is aspect-ratio 16/9 and every clip Arch already has is that shape. I
       had this as 9:16 first, reasoning from the still, which is vertical:
       the still is vertical and gets cropped by object-fit, but a scene
       fills the frame and a vertical one would sit in the middle with bars
       either side. */
    const aspect = body.aspect || '16:9';
    const resolution = body.resolution || '720p';

    /* CROPPED HERE, ONCE, BEFORE ANYTHING ELSE TOUCHES IT -- see cropTo169's
       own note above for why. portrait is reassigned rather than kept
       alongside the original so everything downstream (the stored
       '.portrait' blob a retry reads back, the lastFrame below) uses the
       same already-correct image, with nothing left that could
       accidentally send the uncropped one instead. */
    portrait = await cropTo169(portrait);

    let started;
    try {
      /* SAME IMAGE, BOTH ENDS, added 2026-08-20 for "not a loop so it
         fails." Only ever sent as firstFrameB64 before -- Veo had no target
         to return to and nothing telling it what "seamless" actually meant
         beyond the prompt's own words. Asking it to end on the exact frame
         it started from is a real instruction, not just a description.
         Safe to send unconditionally: _veo-video.js's own ladder already
         tries 'both' first and falls back to first-frame-only automatically
         if a shape/model combination refuses two frames, so this cannot
         make a working render fail. */
      started = await veo.start({
        prompt, firstFrameB64: portrait, lastFrameB64: portrait,
        seconds, models: ladder, aspect, resolution,
      });
    } catch (e) {
      return json(502, { error: 'veo_refused', detail: String(e && e.message || e).slice(0, 500) });
    }

    const operation = started && (started.operation || started.name || started);
    if (!operation || typeof operation !== 'string') {
      return json(502, { error: 'no_operation', detail: JSON.stringify(started).slice(0, 400) });
    }

    const jobId = newJobId();
    /* THE PORTRAIT, KEPT AS ITS OWN BLOB, added 2026-08-20 for automatic
       retry (see the poll handler below). It was never stored before --
       only the order it came from was, and an ad-hoc job with no order_id
       had no portrait anywhere once this request returned. A retry needs
       the exact same first frame, so it has to live somewhere; its own key
       keeps it out of the job's own JSON, which gets read and rewritten on
       every single poll. */
    await store.set(jobId + '.portrait', portrait);
    const job = {
      job_id: jobId,
      status: 'running',
      note: 'Making it. This takes a few minutes.',
      operation,
      seconds,
      model: (started && started.model) || null,
      /* THE HELPER CALLS IT image_field, NOT shape. Reading the wrong name
         reported "image field: null" on a run where the portrait was very much
         attached, which read like the image had been dropped and sent me
         looking in the wrong place when the face came back wrong. */
      image_field: (started && started.image_field) || null,
      cost_cents: (started && started.cost_cents) || null,
      /* KEPT, so a bad result can be diagnosed rather than guessed at. When a
         clip comes back and the face is not theirs, the first question is what
         we actually asked for, and without this there is no way to answer it. */
      prompt,
      aspect,
      resolution,
      models: ladder,
      /* RETRY BOOKKEEPING, added 2026-08-20. See the poll handler: a filtered
         result (Google's raiMediaFilteredReasons, confirmed stochastic by a
         real repro -- same prompt, same portrait, filtered once and then
         succeeded on a second try) restarts the render automatically rather
         than refunding on the first miss. */
      attempts: 1,
      started_at: new Date().toISOString(),
      order_id: (order && order.order_id) || null,
      video_key: null,
      bytes: 0,
      error: null,
    };
    await store.setJSON(jobId, job);
    return json(200, { ok: true, job_id: jobId, seconds, model: job.model, image_field: job.image_field, cost_cents: job.cost_cents });
  }

  /* ── report on one, and finish it ──────────────────────────────────────── */
  const jobId = String(qs.job_id || body.job_id || '').trim();
  if (!/^gcs-[0-9a-f]+$/i.test(jobId)) return json(400, { error: 'job_id_required' });

  let job;
  try { job = await store.get(jobId, { type: 'json' }); } catch (_) { job = null; }
  if (!job) return json(404, { error: 'not_found' });

  /* Hand back the file itself. Veo's own URI sits behind the API key and can
     never be given to a browser, so it is served from here. */
  if (qs.file) {
    if (!job.video_key) return json(409, { error: 'not_ready' });
    const got = await store.get(job.video_key, { type: 'arrayBuffer' });
    if (!got) return json(404, { error: 'file_missing' });
    const mp4 = Buffer.from(got);

    /* RANGE REQUESTS, SO THIS IS A REAL VIDEO SOURCE.
       ─────────────────────────────────────────────────────────────────────
       The first scene was delivered as a static file in the repo because a
       function reply supports no range requests and some browsers will not
       play a video without them. That is fine for one clip made by hand and
       impossible for a made-to-order add-on: every scene would need a commit
       and a deploy before the person who paid could see it.

       Answering ranges here is what makes automatic delivery possible. Safari
       in particular asks for bytes=0-1 first and gives up on a 200. */
    const head = { ...CORS, 'Content-Type': 'video/mp4', 'Accept-Ranges': 'bytes',
                   'Cache-Control': 'public, max-age=31536000, immutable' };

    const range = (event.headers && (event.headers.range || event.headers.Range)) || '';
    const m = /^bytes=(\d*)-(\d*)$/.exec(String(range).trim());
    if (m) {
      let start = m[1] === '' ? null : parseInt(m[1], 10);
      let end   = m[2] === '' ? null : parseInt(m[2], 10);
      /* "bytes=-500" means the LAST 500, not from zero to 500. */
      if (start === null && end !== null) { start = Math.max(0, mp4.length - end); end = mp4.length - 1; }
      if (start === null) start = 0;
      if (end === null || end >= mp4.length) end = mp4.length - 1;

      if (start >= mp4.length || start > end) {
        return { statusCode: 416, headers: { ...head, 'Content-Range': 'bytes */' + mp4.length }, body: '' };
      }
      const slice = mp4.subarray(start, end + 1);
      return {
        statusCode: 206,
        headers: { ...head,
          'Content-Range': 'bytes ' + start + '-' + end + '/' + mp4.length,
          'Content-Length': String(slice.length) },
        body: slice.toString('base64'),
        isBase64Encoded: true,
      };
    }

    return {
      statusCode: 200,
      headers: { ...head, 'Content-Length': String(mp4.length) },
      body: mp4.toString('base64'),
      isBase64Encoded: true,
    };
  }

  if (job.status === 'running' && job.operation) {
    try {
      const res = await veo.check(job.operation);
      if (res.done && res.filtered && (job.attempts || 1) < MAX_VEO_ATTEMPTS) {
        /* RETRIED, NOT REFUNDED, added 2026-08-20. Confirmed by a real repro
           against Isabelle's own stuck order (see _veo-video.js's own note on
           raiMediaFilteredReasons): the exact same prompt and the exact same
           portrait filtered once and then succeeded on the very next try, and
           Google's own message says "you have not been charged for this
           attempt" -- so a retry costs nothing and is worth doing before ever
           telling a paying customer their scene failed. job.status stays
           'running' throughout; only job.operation and job.attempts change,
           so the very next poll just picks up the new operation like any
           other in-progress job. */
        console.log('[gc-scene] job ' + jobId + ' filtered on attempt ' + (job.attempts || 1) + ', retrying: ' + res.error);
        try {
          /* Already cropped to 16:9 (see cropTo169 at the top of this file):
             this blob was written AFTER that crop ran on the original POST,
             never before it. Same image on both ends here too, matching the
             very first attempt exactly. */
          const portraitB64 = String(await store.get(jobId + '.portrait', { type: 'text' }) || '');
          if (!portraitB64) throw new Error('no stored portrait to retry with');
          const retryStarted = await veo.start({
            prompt: job.prompt, firstFrameB64: portraitB64, lastFrameB64: portraitB64, seconds: job.seconds,
            models: (job.models && job.models.length) ? job.models : [veo.MODEL_LITE],
            aspect: job.aspect || '16:9', resolution: job.resolution || '720p',
          });
          job.operation = retryStarted && (retryStarted.operation || retryStarted.name);
          job.attempts = (job.attempts || 1) + 1;
          await store.setJSON(jobId, job);
        } catch (e) {
          /* job.operation is left pointing at the already-filtered result, so
             the next poll just sees the same filtered response and tries this
             same retry again -- attempts was never incremented here, so this
             cannot loop past MAX_VEO_ATTEMPTS. */
          console.warn('[gc-scene] retry-start failed for job ' + jobId + ':', e && e.message);
        }
      } else if (res.done && res.error) {
        job.status = 'error';
        job.error = String(res.error).slice(0, 1200);
        job.note = 'It could not be made.';
        /* LOGGED IN FULL, added 2026-08-20: the same invisible-failure shape
           as gc-chat.js's credit rejections yesterday. job.error was already
           trimmed to a short message for the customer-facing side; this is
           the complete raw thing Google actually sent, console-only, so a
           real diagnosis is possible next time instead of staring at one
           sentence again. */
        console.error('[gc-scene] job ' + jobId + ' failed, full detail:', JSON.stringify(res.error_detail || res.error));
        await store.setJSON(jobId, job);

        /* THE REFUND, ON THE SAME FAILURE THAT USED TO JUST SIT HERE. Only
           for a job that actually came from a paid order, and only once --
           this whole block is gated on job.status === 'running' at the top
           of the function, and this is the line that moves it to 'error',
           so no later poll of the same job can ever re-enter here. The
           order.status === 'paid' check below is the second guard: an
           order already 'refunded' or 'made' is left alone. */
        if (job.order_id) {
          try {
            const orders = getStore('gc_scene_orders');
            const order = await orders.get(job.order_id, { type: 'json' });
            if (order && order.status === 'paid') {
              const result = await refundOrder(order, 'The scene could not be made: ' + job.error);
              console.log('[gc-scene] order ' + order.order_id + ' refund:',
                          result.refunded ? result.refund_id : 'FAILED - ' + result.reason);
            }
          } catch (e) {
            console.warn('[gc-scene] could not refund order for failed job:', e && e.message);
          }
        }
      } else if (res.done && res.uri) {
        /* Claimed first, so two overlapping polls cannot both download and
           pay for the same thing twice over. */
        if (job.note !== 'Saving it.') {
          job.note = 'Saving it.';
          await store.setJSON(jobId, job);
          const mp4 = await veo.download(res.uri);
          await store.set(jobId + '.mp4', mp4, { metadata: { contentType: 'video/mp4' } });
          job.status = 'ready';
          job.video_key = jobId + '.mp4';
          job.bytes = mp4.length;
          job.note = 'Ready.';
          await store.setJSON(jobId, job);

          /* DELIVERED, NOT JUST FINISHED. A scene that exists and has not
             reached the person who paid for it is not done, and the only way
             it used to reach them was somebody remembering to send a link.

             The link is the delivery: a built friend lives in their browser
             rather than an account, so this email IS the handover. If they
             left no address it says so and stays waiting to be sent by hand,
             which is a real outcome rather than a failure. Never fatal: the
             clip is saved either way and can be sent again. */
          if (job.order_id) {
            try {
              const orders = getStore('gc_scene_orders');
              const order = await orders.get(job.order_id, { type: 'json' });
              if (order && order.status !== 'made') {
                const link = 'https://emerging-tech-lab.com/good-company/room.html' +
                  '?add-scene=' + encodeURIComponent('/.netlify/functions/gc-scene?job_id=' + jobId + '&file=1') +
                  '&label=' + encodeURIComponent('A new scene');
                const told = await notify.sceneReady(order, link);
                order.status = 'made';
                order.job_id = jobId;
                order.link = link;
                order.told = told;
                await orders.setJSON(order.order_id, order);
                console.log('[gc-scene] order ' + order.order_id + ' delivered:',
                            told.sent ? told.to : 'not sent (' + told.reason + ')');
              }
            } catch (e) {
              console.warn('[gc-scene] could not close the order:', e && e.message);
            }
          }
        }
      }
    } catch (e) {
      /* A failed poll is not a failed job: Veo goes briefly unreachable and
         the next poll picks it up. Recorded, never fatal. */
      console.warn('[gc-scene] poll failed, will retry:', e && e.message);
    }
  }

  return json(200, {
    ok: true,
    job_id: jobId,
    status: job.status,
    note: job.note,
    seconds: job.seconds,
    model: job.model,
    image_field: job.image_field,
    cost_cents: job.cost_cents,
    prompt: job.prompt || null,
    bytes: job.bytes,
    error: job.error,
    url: job.status === 'ready' ? ('/.netlify/functions/gc-scene?job_id=' + jobId + '&file=1') : null,
  });
};
