/* gc-scene — make a moving scene for somebody's friend, and report on one.
   ─────────────────────────────────────────────────────────────────────────
   POST { owner_key, portrait, where, seconds }  -> { job_id }
   GET  ?job_id=...                              -> { status, note, ready }
   GET  ?job_id=...&file=1                       -> the mp4 itself

   A friend you build comes with one still picture. This is what turns a
   picture into a scene, and it is the machinery behind the Scene two, three,
   four, five slots in the room.

   NO BACKGROUND FUNCTION, copied deliberately from etl-design-animate, which
   learned this the hard way: starting a Veo render is a sub-second call that
   returns an operation name, so POST does it directly, and GET polls that
   operation and finishes the job when it is done. Handing off to a background
   worker gave six runs in a row that reported 'running' and then sat on
   'queued' forever, because Netlify answered the invocation with 202 and never
   ran it. The thing that completes the job is the thing already asking about
   it, so there is no invocation left to fail silently.

   THEY HAVE TO LOOK UP. Dr. O rejected a finished clip of Arch doing woodwork
   for exactly one reason: "he never looked up. I could not have that for a
   companion video." A person absorbed in a task is footage of somebody who
   does not know you are there, and a scene is supposed to be somebody sitting
   WITH you. That instruction is added to every prompt here rather than left to
   whoever writes the description, because getting it wrong costs a whole
   render and only shows up at the end.

   IT SPENDS REAL MONEY, SO IT IS OWNER ONLY. Veo Lite takes an input frame at
   five cents a second, which is the whole reason this is affordable, and the
   ladder in _veo-video.js steps up to the standard tier at forty if Lite
   refuses. Four seconds is twenty cents at best and a pound sixty at worst,
   per press. No visitor gets to spend that: scenes are sold and then made,
   not generated by anybody who finds the endpoint.
*/

const { getStore, connectLambda } = require('@netlify/blobs');
const veo = require('./_veo-video.js');

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization',
};

const json = (status, obj) => ({
  statusCode: status,
  headers: { ...CORS, 'Content-Type': 'application/json', 'Cache-Control': 'no-store' },
  body: JSON.stringify(obj),
});

const STORE = 'gc_scene_jobs';

/* Every prompt gets this, whatever the caller asked for. See the note above. */
const LOOKING_AT_YOU =
  ' They are facing the camera and looking at it, present with the person watching, ' +
  'as though sitting with them. Not absorbed in a task, not looking down, not looking ' +
  'away. Small natural movement: breathing, blinking, an occasional shift or a slight ' +
  'smile. They are keeping somebody company. No speech, no talking, mouth closed or ' +
  'barely moving. The camera does not move.';

function newJobId() {
  /* Unguessable, because the GET side is not owner-gated: knowing a job id is
     how the browser that started it collects the result. */
  const r = require('crypto').randomBytes(9).toString('hex');
  return 'gcs-' + r;
}

exports.handler = async (event) => {
  if (event.httpMethod === 'OPTIONS') return { statusCode: 204, headers: CORS, body: '' };

  const qs = event.queryStringParameters || {};
  let body = {};
  try { body = JSON.parse(event.body || '{}'); } catch (_) {}

  try { connectLambda(event); } catch (_) {}
  let store;
  try { store = getStore(STORE); } catch (e) { return json(500, { error: 'store_unavailable' }); }

  /* ── start one ─────────────────────────────────────────────────────────── */
  if (event.httpMethod === 'POST') {
    const owner = String(body.owner_key || '').trim();
    if (!process.env.OWNER_KEY || owner !== process.env.OWNER_KEY) {
      return json(403, { error: 'owner_only' });
    }

    /* The still to animate. Sent as base64 without a data: prefix, because
       that is what Veo takes and stripping it here means the caller does not
       have to know that. */
    let portrait = String(body.portrait || '');
    portrait = portrait.replace(/^data:image\/[a-z+]+;base64,/i, '').trim();
    if (!portrait) return json(400, { error: 'portrait_required' });

    const where = String(body.where || '').trim();
    if (!where) return json(400, { error: 'where_required' });

    /* Four seconds by default and eight at most. Duration is the only real
       lever on what this costs, and the helper clamps it too. */
    const seconds = Math.min(8, Math.max(4, Number(body.seconds) || 4));

    /* LITE OR NOTHING, UNLESS SOMEBODY SAYS OTHERWISE IN SO MANY WORDS.
       The shared ladder steps Lite up to the standard tier on a refusal, which
       is eight times the price: four seconds goes from twenty cents to a pound
       sixty, and four scenes from $1.60 to $12.80. Dr. O on that number: "no".

       So the ceiling is explicit here. A refusal comes back as a refusal, which
       costs nothing, and stepping up is a decision somebody makes on purpose by
       sending allow_standard rather than something discovered from a bill. */
    const ladder = body.allow_standard ? [veo.MODEL_LITE, veo.MODEL_FULL] : [veo.MODEL_LITE];

    let started;
    try {
      started = await veo.start({
        prompt: where + LOOKING_AT_YOU,
        firstFrameB64: portrait,
        seconds,
        models: ladder,
        /* SIXTEEN BY NINE, BECAUSE THAT IS THE SHAPE OF THE ROOM. The video
           area is aspect-ratio 16/9 and every clip Arch already has is that
           shape. I had this as 9:16 first, reasoning from the still, which is
           vertical: the still is vertical and gets cropped by object-fit, but a
           scene fills the frame and a vertical one would sit in the middle with
           bars either side. */
        aspect: body.aspect || '16:9',
      });
    } catch (e) {
      return json(502, { error: 'veo_refused', detail: String(e && e.message || e).slice(0, 500) });
    }

    const operation = started && (started.operation || started.name || started);
    if (!operation || typeof operation !== 'string') {
      return json(502, { error: 'no_operation', detail: JSON.stringify(started).slice(0, 400) });
    }

    const jobId = newJobId();
    const job = {
      job_id: jobId,
      status: 'running',
      note: 'Making it. This takes a few minutes.',
      operation,
      seconds,
      model: (started && started.model) || null,
      shape: (started && started.shape) || null,
      started_at: new Date().toISOString(),
      video_key: null,
      bytes: 0,
      error: null,
    };
    await store.setJSON(jobId, job);
    return json(200, { ok: true, job_id: jobId, seconds, model: job.model, shape: job.shape });
  }

  /* ── report on one, and finish it ──────────────────────────────────────── */
  const jobId = String(qs.job_id || body.job_id || '').trim();
  if (!/^gcs-[0-9a-f]+$/i.test(jobId)) return json(400, { error: 'job_id_required' });

  let job;
  try { job = await store.get(jobId, { type: 'json' }); } catch (_) { job = null; }
  if (!job) return json(404, { error: 'not_found' });

  /* Hand back the file itself. Veo's own URI sits behind the API key and can
     never be given to a browser, so it is served from here. */
  if (qs.file) {
    if (!job.video_key) return json(409, { error: 'not_ready' });
    const mp4 = await store.get(job.video_key, { type: 'arrayBuffer' });
    if (!mp4) return json(404, { error: 'file_missing' });
    return {
      statusCode: 200,
      headers: { ...CORS, 'Content-Type': 'video/mp4', 'Cache-Control': 'public, max-age=31536000, immutable' },
      body: Buffer.from(mp4).toString('base64'),
      isBase64Encoded: true,
    };
  }

  if (job.status === 'running' && job.operation) {
    try {
      const res = await veo.check(job.operation);
      if (res.done && res.error) {
        job.status = 'error';
        job.error = String(res.error).slice(0, 1200);
        job.note = 'It could not be made.';
        await store.setJSON(jobId, job);
      } else if (res.done && res.uri) {
        /* Claimed first, so two overlapping polls cannot both download and
           pay for the same thing twice over. */
        if (job.note !== 'Saving it.') {
          job.note = 'Saving it.';
          await store.setJSON(jobId, job);
          const mp4 = await veo.download(res.uri);
          await store.set(jobId + '.mp4', mp4, { metadata: { contentType: 'video/mp4' } });
          job.status = 'ready';
          job.video_key = jobId + '.mp4';
          job.bytes = mp4.length;
          job.note = 'Ready.';
          await store.setJSON(jobId, job);
        }
      }
    } catch (e) {
      /* A failed poll is not a failed job: Veo goes briefly unreachable and
         the next poll picks it up. Recorded, never fatal. */
      console.warn('[gc-scene] poll failed, will retry:', e && e.message);
    }
  }

  return json(200, {
    ok: true,
    job_id: jobId,
    status: job.status,
    note: job.note,
    seconds: job.seconds,
    model: job.model,
    shape: job.shape,
    bytes: job.bytes,
    error: job.error,
    url: job.status === 'ready' ? ('/.netlify/functions/gc-scene?job_id=' + jobId + '&file=1') : null,
  });
};
