/* gc-scene — make a moving scene for somebody's friend, and report on one.
   ─────────────────────────────────────────────────────────────────────────
   POST { owner_key, portrait, where, seconds }  -> { job_id }
   GET  ?job_id=...                              -> { status, note, ready }
   GET  ?job_id=...&file=1                       -> the mp4 itself

   A friend you build comes with one still picture. This is what turns a
   picture into a scene, and it is the machinery behind the Scene two, three,
   four, five slots in the room.

   NO BACKGROUND FUNCTION, copied deliberately from etl-design-animate, which
   learned this the hard way: starting a Veo render is a sub-second call that
   returns an operation name, so POST does it directly, and GET polls that
   operation and finishes the job when it is done. Handing off to a background
   worker gave six runs in a row that reported 'running' and then sat on
   'queued' forever, because Netlify answered the invocation with 202 and never
   ran it. The thing that completes the job is the thing already asking about
   it, so there is no invocation left to fail silently.

   THEY HAVE TO LOOK UP. Dr. O rejected a finished clip of Arch doing woodwork
   for exactly one reason: "he never looked up. I could not have that for a
   companion video." A person absorbed in a task is footage of somebody who
   does not know you are there, and a scene is supposed to be somebody sitting
   WITH you. That instruction is added to every prompt here rather than left to
   whoever writes the description, because getting it wrong costs a whole
   render and only shows up at the end.

   IT SPENDS REAL MONEY, SO IT IS OWNER ONLY. Veo Lite takes an input frame at
   five cents a second, which is the whole reason this is affordable, and the
   ladder in _veo-video.js steps up to the standard tier at forty if Lite
   refuses. Four seconds is twenty cents at best and a pound sixty at worst,
   per press. No visitor gets to spend that: scenes are sold and then made,
   not generated by anybody who finds the endpoint.
*/

const { getStore, connectLambda } = require('@netlify/blobs');
const veo = require('./_veo-video.js');

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization',
};

const json = (status, obj) => ({
  statusCode: status,
  headers: { ...CORS, 'Content-Type': 'application/json', 'Cache-Control': 'no-store' },
  body: JSON.stringify(obj),
});

const STORE = 'gc_scene_jobs';

/* ── THE PROMPT THAT ALREADY WORKS ───────────────────────────────────────────
   Not invented here. This is Dr. O's own wording from the Flow sessions that
   produced Arch's five clips, which she made by hand with no editing after and
   judged "perfectly fine". Automating that means using her prompt, not a
   reasonable-sounding one of mine.

   Hers, verbatim in shape: "A seamless infinite loop of this man sitting in
   front of a wood fireplace in a log cabin, but have him look over at the
   camera. Static camera, fixed framing, consistent soft lighting throughout.
   Minimal body movement."

   THE LOOP IS THE PART I HAD MISSED. The room plays these with the loop
   attribute, so a clip that does not end where it began jumps every few
   seconds and the person twitches. Every one of her prompts opens with
   "a seamless infinite loop" and that is why hers sit quietly under a
   conversation.

   FIXED FRAMING AND CONSISTENT LIGHTING do the same job: across a loop point,
   a drifting camera or a changing light is exactly where the seam shows.

   LOOKING AT THE CAMERA is hers too, in every prompt, and it is the thing she
   rejected a finished clip over.

   HER TEMPLATE, WITH ONE SLOT. Given exactly:

     "A seamless infinite loop of this man [sitting in front of a wood
      fireplace in a log cabin]. Static camera, fixed framing, consistent soft
      lighting throughout. Minimal body movement, fluid and natural repetition
      where the ending seamlessly matches the starting frame, no jump cuts. Do
      not change his looks, but change his clothes to a plaid shirt and jeans."

   Everything outside the bracket is fixed and the caller fills the bracket.
   Writing it any other way is how a proven prompt quietly becomes a different
   one.

   DO NOT CHANGE HIS LOOKS is the line I would not have thought to write and
   the one that matters most. Somebody chose that face out of four. A scene
   that drifts it is not their friend any more, and the drift would arrive
   looking like a quality problem rather than the identity problem it is.

   THE ENDING MATCHING THE STARTING FRAME is the loop said twice, from both
   ends. The room plays these on loop and the seam is the whole risk. */

function scenePrompt({ where, gender, clothes }) {
  /* "this man" is hers because Arch is one. The friend carries a gender and
     the prompt has to follow it, or every woman somebody builds is described
     to the model as a man. */
  const g = String(gender || '').toLowerCase();
  const isWoman = /woman|female|she/.test(g);
  const isMan   = !isWoman && /man|male|\bhe\b/.test(g);
  const subject = isWoman ? 'this woman' : isMan ? 'this man' : 'this person';

  /* PRONOUNS FOLLOW THE SUBJECT. It read "this man ... They look over", which
     is a small inconsistency to hand a model whose one hard instruction is not
     to change who it is looking at. */
  const single = isWoman || isMan;              // "they" takes plural verbs
  const they  = isWoman ? 'She'  : isMan ? 'He'  : 'They';
  const their = isWoman ? 'her'   : isMan ? 'his' : 'their';
  const are   = single ? 'is' : 'are';
  const looks = single ? 'looks' : 'look';
  const stays = single ? 'stays' : 'stay';

  const bits = [];
  bits.push('A seamless infinite loop of ' + subject + ' ' + String(where).trim().replace(/\.$/, '') + '.');
  bits.push('Static camera, fixed framing, consistent soft lighting throughout.');
  bits.push('Minimal body movement, fluid and natural repetition where the ending seamlessly ' +
            'matches the starting frame, no jump cuts.');

  /* LOOKING AT THE CAMERA sits in every Flow prompt she wrote, worded into the
     scene itself: "but have him look over at the camera". It is not optional
     and it is not the caller's to forget, because she rejected a finished clip
     over precisely this and a render only reveals it at the end. */
  bits.push(they + ' ' + looks + ' over at the camera and ' + stays + ' with the person ' +
            'watching, present, as though sitting with them. Not absorbed in a task, not ' +
            'looking away. ' + they + ' ' + are + ' not talking and there is no speech.');

  /* Her last clause, and optional the way she used it. */
  bits.push(clothes
    ? 'Do not change ' + their + ' looks, but change ' + their + ' clothes to ' +
      String(clothes).trim().replace(/\.$/, '') + '.'
    : 'Do not change ' + their + ' looks.');

  return bits.join(' ');
}

function newJobId() {
  /* Unguessable, because the GET side is not owner-gated: knowing a job id is
     how the browser that started it collects the result. */
  const r = require('crypto').randomBytes(9).toString('hex');
  return 'gcs-' + r;
}

exports.handler = async (event) => {
  if (event.httpMethod === 'OPTIONS') return { statusCode: 204, headers: CORS, body: '' };

  const qs = event.queryStringParameters || {};
  let body = {};
  try { body = JSON.parse(event.body || '{}'); } catch (_) {}

  try { connectLambda(event); } catch (_) {}
  let store;
  try { store = getStore(STORE); } catch (e) { return json(500, { error: 'store_unavailable' }); }

  /* ── start one ─────────────────────────────────────────────────────────── */
  if (event.httpMethod === 'POST') {
    const owner = String(body.owner_key || '').trim();
    if (!process.env.OWNER_KEY || owner !== process.env.OWNER_KEY) {
      return json(403, { error: 'owner_only' });
    }

    /* The still to animate. Sent as base64 without a data: prefix, because
       that is what Veo takes and stripping it here means the caller does not
       have to know that. */
    let portrait = String(body.portrait || '');
    portrait = portrait.replace(/^data:image\/[a-z+]+;base64,/i, '').trim();

    let where = String(body.where || '').trim();
    let gender = body.gender;
    let order = null;

    /* FULFILLING AN ORDER, WITHOUT MOVING THE PICTURE BY HAND. Somebody asked
       for a scene through gc-scene-order and their portrait is already stored;
       passing order_id here reads it back rather than making whoever is
       fulfilling it download a megabyte and paste it into a request. What they
       asked for comes with it, so the scene made is the scene ordered. */
    if (body.order_id) {
      const orders = getStore('gc_scene_orders');
      order = await orders.get(String(body.order_id), { type: 'json' });
      if (!order) return json(404, { error: 'order_not_found' });
      if (!portrait) {
        portrait = String(await orders.get(order.portrait_key, { type: 'text' }) || '').trim();
      }
      if (!where) where = order.where;
      if (!gender) gender = order.gender;
    }

    if (!portrait) return json(400, { error: 'portrait_required' });
    if (!where) return json(400, { error: 'where_required' });

    /* Four seconds by default and eight at most. Duration is the only real
       lever on what this costs, and the helper clamps it too. */
    const seconds = Math.min(8, Math.max(4, Number(body.seconds) || 4));

    /* LITE OR NOTHING, UNLESS SOMEBODY SAYS OTHERWISE IN SO MANY WORDS.
       The shared ladder steps Lite up to the standard tier on a refusal, which
       is eight times the price: four seconds goes from twenty cents to a pound
       sixty, and four scenes from $1.60 to $12.80. Dr. O on that number: "no".

       So the ceiling is explicit here. A refusal comes back as a refusal, which
       costs nothing, and stepping up is a decision somebody makes on purpose by
       sending allow_standard rather than something discovered from a bill. */
    const ladder = body.allow_standard ? [veo.MODEL_LITE, veo.MODEL_FULL] : [veo.MODEL_LITE];

    const prompt = scenePrompt({ where, gender, clothes: body.clothes });

    let started;
    try {
      started = await veo.start({
        prompt,
        firstFrameB64: portrait,
        seconds,
        models: ladder,
        /* SIXTEEN BY NINE, BECAUSE THAT IS THE SHAPE OF THE ROOM. The video
           area is aspect-ratio 16/9 and every clip Arch already has is that
           shape. I had this as 9:16 first, reasoning from the still, which is
           vertical: the still is vertical and gets cropped by object-fit, but a
           scene fills the frame and a vertical one would sit in the middle with
           bars either side. */
        aspect: body.aspect || '16:9',
        resolution: body.resolution || '720p',
      });
    } catch (e) {
      return json(502, { error: 'veo_refused', detail: String(e && e.message || e).slice(0, 500) });
    }

    const operation = started && (started.operation || started.name || started);
    if (!operation || typeof operation !== 'string') {
      return json(502, { error: 'no_operation', detail: JSON.stringify(started).slice(0, 400) });
    }

    const jobId = newJobId();
    const job = {
      job_id: jobId,
      status: 'running',
      note: 'Making it. This takes a few minutes.',
      operation,
      seconds,
      model: (started && started.model) || null,
      /* THE HELPER CALLS IT image_field, NOT shape. Reading the wrong name
         reported "image field: null" on a run where the portrait was very much
         attached, which read like the image had been dropped and sent me
         looking in the wrong place when the face came back wrong. */
      image_field: (started && started.image_field) || null,
      cost_cents: (started && started.cost_cents) || null,
      /* KEPT, so a bad result can be diagnosed rather than guessed at. When a
         clip comes back and the face is not theirs, the first question is what
         we actually asked for, and without this there is no way to answer it. */
      prompt,
      started_at: new Date().toISOString(),
      order_id: (order && order.order_id) || null,
      video_key: null,
      bytes: 0,
      error: null,
    };
    await store.setJSON(jobId, job);
    return json(200, { ok: true, job_id: jobId, seconds, model: job.model, image_field: job.image_field, cost_cents: job.cost_cents });
  }

  /* ── report on one, and finish it ──────────────────────────────────────── */
  const jobId = String(qs.job_id || body.job_id || '').trim();
  if (!/^gcs-[0-9a-f]+$/i.test(jobId)) return json(400, { error: 'job_id_required' });

  let job;
  try { job = await store.get(jobId, { type: 'json' }); } catch (_) { job = null; }
  if (!job) return json(404, { error: 'not_found' });

  /* Hand back the file itself. Veo's own URI sits behind the API key and can
     never be given to a browser, so it is served from here. */
  if (qs.file) {
    if (!job.video_key) return json(409, { error: 'not_ready' });
    const mp4 = await store.get(job.video_key, { type: 'arrayBuffer' });
    if (!mp4) return json(404, { error: 'file_missing' });
    return {
      statusCode: 200,
      headers: { ...CORS, 'Content-Type': 'video/mp4', 'Cache-Control': 'public, max-age=31536000, immutable' },
      body: Buffer.from(mp4).toString('base64'),
      isBase64Encoded: true,
    };
  }

  if (job.status === 'running' && job.operation) {
    try {
      const res = await veo.check(job.operation);
      if (res.done && res.error) {
        job.status = 'error';
        job.error = String(res.error).slice(0, 1200);
        job.note = 'It could not be made.';
        await store.setJSON(jobId, job);
      } else if (res.done && res.uri) {
        /* Claimed first, so two overlapping polls cannot both download and
           pay for the same thing twice over. */
        if (job.note !== 'Saving it.') {
          job.note = 'Saving it.';
          await store.setJSON(jobId, job);
          const mp4 = await veo.download(res.uri);
          await store.set(jobId + '.mp4', mp4, { metadata: { contentType: 'video/mp4' } });
          job.status = 'ready';
          job.video_key = jobId + '.mp4';
          job.bytes = mp4.length;
          job.note = 'Ready.';
          await store.setJSON(jobId, job);
        }
      }
    } catch (e) {
      /* A failed poll is not a failed job: Veo goes briefly unreachable and
         the next poll picks it up. Recorded, never fatal. */
      console.warn('[gc-scene] poll failed, will retry:', e && e.message);
    }
  }

  return json(200, {
    ok: true,
    job_id: jobId,
    status: job.status,
    note: job.note,
    seconds: job.seconds,
    model: job.model,
    image_field: job.image_field,
    cost_cents: job.cost_cents,
    prompt: job.prompt || null,
    bytes: job.bytes,
    error: job.error,
    url: job.status === 'ready' ? ('/.netlify/functions/gc-scene?job_id=' + jobId + '&file=1') : null,
  });
};
