const http = require('http');
const {
  Document, Packer, Paragraph, TextRun, HeadingLevel,
  AlignmentType, Footer, BorderStyle, PageNumberElement
} = require('docx');

const FONT = 'Times New Roman';
const BODY_SIZE = 24;
const H1_SIZE = 32;

function textToParas(text) {
  if (!text) return [new Paragraph({
    children: [new TextRun({ text: '[Not yet generated]', italics: true, color: '999999', font: FONT, size: BODY_SIZE })],
    spacing: { after: 240 }
  })];
  return text.split(/\n\n+/).filter(p => p.trim()).map(block =>
    new Paragraph({
      children: block.split('\n').flatMap((line, i) => [
        ...(i > 0 ? [new TextRun({ break: 1 })] : []),
        new TextRun({ text: line, font: FONT, size: BODY_SIZE })
      ]),
      indent: { firstLine: 720 },
      spacing: { after: 240 },
      alignment: AlignmentType.JUSTIFIED
    })
  );
}

function buildDoc(input) {
  const { sections, topic, mode, citationStyle, refHeading, timestamp, references, posterMeta } = input;
  const modeLabel = mode === 'thesis' ? 'Thesis & Dissertation Draft'
                  : mode === 'poster' ? 'Academic Poster Draft'
                  : 'Systematic Literature Review Draft';
  const children = [];

  // Title block
  children.push(new Paragraph({
    children: [new TextRun({ text: modeLabel, bold: true, font: FONT, size: 36 })],
    alignment: AlignmentType.CENTER, spacing: { after: 120 }
  }));
  children.push(new Paragraph({
    children: [new TextRun({ text: `Generated by SLR Studio · ${timestamp}`, font: FONT, size: 18, color: '888888' })],
    alignment: AlignmentType.CENTER, spacing: { after: 120 }
  }));
  children.push(new Paragraph({
    children: [new TextRun({ text: `Topic: ${topic || ''}`, italics: true, font: FONT, size: BODY_SIZE })],
    alignment: AlignmentType.CENTER, spacing: { after: 120 }
  }));
  children.push(new Paragraph({
    children: [new TextRun({ text: `Citation Style: ${citationStyle || 'APA 7'}`, font: FONT, size: BODY_SIZE, color: '555555' })],
    alignment: AlignmentType.CENTER, spacing: { after: 720 },
    border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: 'CCCCCC', space: 8 } }
  }));

  // Sections
  (sections || []).forEach(sec => {
    children.push(new Paragraph({
      text: `${sec.num !== '—' ? sec.num + '. ' : ''}${sec.title}`,
      heading: HeadingLevel.HEADING_1,
      spacing: { before: 480, after: 200 }
    }));
    if (sec.hint) {
      children.push(new Paragraph({
        children: [new TextRun({ text: `Guidance: ${sec.hint}`, italics: true, font: FONT, size: 18, color: '888888' })],
        spacing: { after: 200 }
      }));
    }
    children.push(...textToParas(sec.text));
  });

  // References
  if (references && references.length > 0) {
    children.push(new Paragraph({
      text: refHeading || 'References',
      heading: HeadingLevel.HEADING_1,
      spacing: { before: 720, after: 240 }
    }));
    references.forEach(ref => {
      children.push(new Paragraph({
        children: [new TextRun({ text: ref, font: FONT, size: BODY_SIZE })],
        indent: { left: 720, hanging: 720 },
        spacing: { after: 200 }
      }));
    });
  }

  // Poster metadata
  if (mode === 'poster' && posterMeta) {
    const m = posterMeta;
    const fields = [['Presenter(s)',m.authors],['Institution',m.institution],['Contact',m.contact],['Conference',m.conference],['Grant / Funding',m.grants],['Acknowledgements',m.acknowledgements],['QR Code URL',m.qr]];
    const hasAny = fields.some(([,v]) => v && v.trim());
    if (hasAny) {
      children.push(new Paragraph({ text: 'Poster Metadata', heading: HeadingLevel.HEADING_1, spacing: { before: 720, after: 240 } }));
      fields.filter(([,v]) => v && v.trim()).forEach(([label, value]) => {
        children.push(new Paragraph({
          children: [new TextRun({ text: `${label}: `, bold: true, font: FONT, size: BODY_SIZE }), new TextRun({ text: value, font: FONT, size: BODY_SIZE })],
          spacing: { after: 160 }
        }));
      });
    }
  }

  const footerPara = new Paragraph({
    children: [new TextRun({ text: 'SLR Studio · ETL · Wright State University · Page ', font: FONT, size: 18, color: '888888' }), new TextRun({ children: [new PageNumberElement()], font: FONT, size: 18, color: '888888' })],
    alignment: AlignmentType.CENTER
  });

  return new Document({
    styles: {
      default: { document: { run: { font: FONT, size: BODY_SIZE } } },
      paragraphStyles: [
        { id: 'Heading1', name: 'Heading 1', basedOn: 'Normal', next: 'Normal', quickFormat: true,
          run: { size: H1_SIZE, bold: true, font: FONT, color: '1a1a2e' },
          paragraph: { spacing: { before: 400, after: 200 }, outlineLevel: 0 } }
      ]
    },
    sections: [{
      properties: { page: { size: { width: 12240, height: 15840 }, margin: { top: 1440, right: 1440, bottom: 1440, left: 1800 } } },
      footers: { default: new Footer({ children: [footerPara] }) },
      children
    }]
  });
}

const server = http.createServer((req, res) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') { res.writeHead(204); res.end(); return; }
  if (req.method !== 'POST' || req.url !== '/export') { res.writeHead(404); res.end(); return; }

  let body = '';
  req.on('data', chunk => body += chunk);
  req.on('end', () => {
    try {
      const input = JSON.parse(body);
      const doc = buildDoc(input);
      Packer.toBuffer(doc).then(buf => {
        const mode = input.mode || 'review';
        const filename = mode === 'thesis' ? 'Thesis_Draft.docx' : mode === 'poster' ? 'Poster_Draft.docx' : 'SLR_Draft.docx';
        res.writeHead(200, {
          'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
          'Content-Disposition': `attachment; filename="${filename}"`,
          'Content-Length': buf.length
        });
        res.end(buf);
      }).catch(e => { res.writeHead(500); res.end(e.message); });
    } catch(e) { res.writeHead(400); res.end(e.message); }
  });
});

server.listen(7749, '127.0.0.1', () => console.log('SLR docx server running on port 7749'));
